name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['nodejs/03-api-solid'] }
    
    steps:
      - name: Enter to folder
        run: cd nodejs
        

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
        
      - run: yarn ci

      - run: yarn test
